# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyLg2yOZGDtnR_Bkv1C4Dr-tOWLQnwYe
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/WHO COVID-19 cases.csv')

print(df.head())
print(df.info())
print(df.describe())

df.fillna(0, inplace=True)

df['Date_reported'] = pd.to_datetime(df['Date_reported'])


df['Year'] = df['Date_reported'].dt.year

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # Make sure to import matplotlib.pyplot
import seaborn as sns

# Load the dataframe. Make sure the path to your file is correct.
df = pd.read_csv('/WHO COVID-19 cases.csv')

# Visualize the distribution of cases, deaths, and recoveries
plt.figure(figsize=(12, 6))
plt.subplot(1, 3, 1)
plt.hist(df['New_cases'], bins=30, color='blue')
plt.title('Distribution of New Cases')

plt.subplot(1, 3, 2)
plt.hist(df['New_deaths'], bins=30,  color='orange')
plt.title('Distribution of New Deaths')

plt.show()

import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
import matplotlib.pyplot as plt

# Load the dataframe. Make sure the path to your file is correct.
df = pd.read_csv('/WHO COVID-19 cases.csv')

# Assuming you want to forecast 'New_cases'
train_data = df['New_cases'][:int(0.8 * len(df))]
test_data = df['New_cases'][int(0.8 * len(df)):]

model = ARIMA(train_data, order=(1, 1, 1))
model_fit = model.fit()

forecast = model_fit.forecast(steps=len(test_data))

# Use summary() to disp

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_squared_error

df = pd.read_csv('WHO COVID-19 cases.csv')

# Display the first few rows
df.head()

# Get information about the dataset
df.info()

# Generate descriptive statistics
df.describe()

# Fill missing values (if any)
df['New_cases'] = df['New_cases'].fillna(df['New_cases'].mean())

# Assuming 'df' is your DataFrame and 'New_cases' is the column with your time series data
result = seasonal_decompose(df['New_cases'], model='additive', period=12)  # or model='multiplicative'

# Access the components
result.trend
result.seasonal
result.resid

# Plot the decomposed components
result.plot()
plt.show()

# Create seasonal differencing
df['New_cases_diff'] = df['New_cases'].diff(periods=12)  # Assuming monthly seasonality

train_size = int(len(df) * 0.8)
train_data = df.iloc[:train_size]
test_data = df.iloc[train_size:]

# Specify SARIMAX parameters (adjust based on EDA and model diagnostics)
model = SARIMAX(train_data['New_cases_diff'], order=(5,1,0), seasonal_order=(1,0,1,12))

# Fit the model
model_fit = model.fit()

# Make predictions
predictions = model_fit.forecast(steps=len(test_data))

# Invert the differencing (if applicable)
predictions = predictions.cumsum() + train_data['New_cases'].iloc[-1]

# Calculate mean squared error
mse = mean_squared_error(test_data['New_cases'], predictions)
print("Mean Squared Error:", mse)

# Visualize actual vs. predicted values
plt.plot(test_data)
plt.plot(predictions, color='red')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose # Import the missing module
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_squared_error

# Remove the leading space in the file path
df = pd.read_csv('/WHO COVID-19 cases.csv')

# Display the first few rows
df.head()

# Get information about the dataset
df.info()

# Generate descriptive statistics
df.describe()

# Fill missing values (if any)
df['New_cases'] = df['New_cases'].fillna(df['New_cases'].mean())

# Assuming 'df' is your DataFrame and 'New_cases' is the column with your time series data
result = seasonal_decompose(df['New_cases'], model='additive', period=12)  # or model='multiplicative'

# Access the components
result.trend
result.seasonal
result.resid

# Plot the decomposed components
result.plot()
plt.show()

# Create seasonal differencing
df['New_cases_diff'] = df['New_cases'].diff(periods=12)  # Assuming monthly seasonality

train_size = int(len(df) * 0.8)
train_data = df.iloc[:train_size]
test_data = df.iloc[train_size:]

# Specify SARIMAX parameters (adjust based on EDA and model diagnostics)
model = SARIMAX(train_data['New_cases_diff'], order=(5,1,0), seasonal_order=(1,0,1,12))

# Fit the model
model_fit = model.fit()

# Make predictions
predictions = model_fit.forecast(steps=len(test_data))

# Invert the differencing (if applicable)
predictions = predictions.cumsum() + train_data['New_cases'].iloc[-1]

# Calculate mean squared error
mse = mean_squared_error(test_data['New_cases'], predictions)
print("Mean Squared Error:", mse)

# Visualize actual vs. predicted values
plt.plot(test_data['New_cases']) # Specify the column to plot
plt.plot(predictions, color='red')
plt.show()

# Visualize actual vs. predicted values
plt.plot(np.arange(len(test_data)), test_data['New_cases']) # Access the 'New_cases' column of the DataFrame
plt.plot(predictions, color='red')
plt.show()